function showMessage(text, ids = '', large = false){
	var $openedModal = $('.modalAutoGenerated'),
		openedModalLength = $openedModal.length
	if(openedModalLength){
		$openedModal.modal('hide').on('hidden.bs.modal', function(){
			$('body').addClass('modal-open');
		});;
	}
	var msg = '<div class="modal fade modalAutoGenerated" role="dialog"'+ ((ids) ? 'id='+ ids : '') +'><div class="modal-dialog'+ ((large) ? ' modal-lg' : '') +'" role="document"><div class="modal-content"><div class="modal-body">'+ text +'</div></div></div></div>';
	var mod = $(msg).modal().on('hidden.bs.modal', function(){
			$(this).remove();	
		});
	return mod;
}

function returnOrder(event, id){
	var msg = showMessage('Подождите, идет загрузка ...', 'returnOrderDialog', true);
	$.post('/order/getOrder', {id: id}).fail(function(){
		$(msg).find('.modal-body').html('Произошла ошибка. Попробуйте перезагрузить страницу.');
	}).done(function(data){
		console.log(data);
		data = JSON.parse(data);
		if(data.error == 200){
			var msgHTML = 
				'<h1>Закрыть заказ № '+ id +'</h1>'+
				'<b>Автомобиль: </b>'+ data.data.car + '<br>'+
				'<b>Клиент: </b>'+ data.data.client + '<br>'+
				'<form id="returnOrderDialogForm">'+
					'<div class="form-group"><label for="comment">Ваш отзыв</label><textarea class="form-control" name="comment"></textarea></div>'+
					'<div class="form-group"><label for="comment">Ваша оценка</label>'+
						'<select name="mark" class="form-control">'+
							'<option value="5">5</option>'+
							'<option value="4">4</option>'+
							'<option value="3">3</option>'+
							'<option value="2">2</option>'+
							'<option value="1">1</option>'+
						'</select>'+
					'</div>'+
					'<div class="checkbox" style="float:right;"><label><input type="checkbox" name="blacked">Внести клиента в черный список</label></div>'+
					'<input type="hidden" name="orderId" value="'+ id +'">'+
					'<div class="form-group"><input type="submit" value="Закрыть заказ" class="btn btn-success"><button type="button" class="btn btn-default" data-dismiss="modal" style="margin-left: 10px;">Отмена</button></div>'+
				'</form>'
			;
			$(msg).find('.modal-body').html(msgHTML);
		}
	})
}

$(document).ready(function(){

	$(document).on('submit', '#returnOrderDialogForm', function(e){
		e.preventDefault();
		var	$form = $(this),
			$submit = $form.find('[type=submit]').addClass('disabled'),
			$comment = $form.find('[name=comment]'),
			$mark = $form.find('[name=mark]'),
			$orderId = $form.find('[name=orderId]'),
			$blacked = $form.find('[name=blacked]').is(':checked');

		console.log($blacked);

		$.post('/order/return', {order_id: $orderId.val(), mark: $mark.val(), comment: $comment.val(), blacked: $blacked}).fail(function(){
			showMessage('Ошибка, не удалось закрыть заказ.');
		}).done(function(data){
			console.log(data);
			data = JSON.parse(data);
			if(data.error == 200){
				$('#allOrdersList tr[data-order_id='+ $orderId.val() +'] .returnOrderBtn').remove();
				$('#allOrdersList tr[data-order_id='+ $orderId.val() +'] td:last-child').text('Заказ закрыт');
				showMessage('Заказ успешно закрыт!');
			}else
				showMessage('Ошибка, не удалось закрыть заказ.');
		}).always(function(){
			$submit.removeClass('disabled');
		});;
	});

});